
import {
  Project,
  ProjectUpdate,
  SafetyIncident,
  WorkerCertification,
  SafetyTrainingRecord,
  Resource,
  Task,
  Budget,
  Document,
  ComplianceItem,
  CCTVCamera,
  DashboardMetrics,
} from "@/types";

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Metro Manila Residential Complex",
    description: "High-rise residential development with 200 units",
    status: "Active",
    projectManager: "Juan dela Cruz",
    startDate: "2024-01-15",
    endDate: "2025-06-30",
    budget: 150000000,
    progress: 65,
    location: "Makati City, Metro Manila",
    client: "Premium Properties Inc.",
    scopeStatement: "Construction of a 25-story residential complex with amenities",
    riskAssessmentSummary: "Weather delays and material cost fluctuation identified as key risks",
    lessonsLearned: "Early supplier engagement crucial for timeline adherence",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-06-20T00:00:00Z",
  },
  {
    id: "2",
    name: "Cebu Commercial Center",
    description: "Modern shopping and business center",
    status: "Planning",
    projectManager: "Maria Santos",
    startDate: "2024-07-01",
    endDate: "2026-03-15",
    budget: 200000000,
    progress: 15,
    location: "Cebu City, Cebu",
    client: "Cebu Development Corp.",
    scopeStatement: "Construction of mixed-use commercial complex with retail and office spaces",
    riskAssessmentSummary: "Environmental compliance and traffic management during construction",
    lessonsLearned: "Stakeholder engagement essential for project success",
    createdAt: "2024-05-01T00:00:00Z",
    updatedAt: "2024-06-20T00:00:00Z",
  },
  {
    id: "3",
    name: "Davao Infrastructure Project",
    description: "Road and bridge construction project",
    status: "Completed",
    projectManager: "Carlos Reyes",
    startDate: "2023-03-01",
    endDate: "2024-02-29",
    budget: 80000000,
    progress: 100,
    location: "Davao City, Davao del Sur",
    client: "Department of Public Works",
    scopeStatement: "Construction of 5km road extension and 2 bridge structures",
    riskAssessmentSummary: "Monsoon season impact and geotechnical challenges addressed",
    lessonsLearned: "Proper soil analysis prevents costly delays",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
];

export const mockProjectUpdates: ProjectUpdate[] = [
  {
    id: "1",
    projectId: "1",
    title: "Foundation Work Completed",
    content: "All foundation work for Building A has been successfully completed. The concrete has cured properly and inspection reports show excellent quality. Moving to structural framework next week.",
    author: "Juan dela Cruz",
    type: "milestone",
    priority: "high",
    imageUrl: "/placeholder.svg",
    createdAt: "2024-06-20T10:30:00Z",
    updatedAt: "2024-06-20T10:30:00Z",
  },
  {
    id: "2",
    projectId: "1",
    title: "Weather Delays Expected",
    content: "Typhoon Falcon is approaching and may cause 2-3 days delay in exterior work. All equipment has been secured and workers briefed on safety protocols.",
    author: "Safety Officer Rodriguez",
    type: "issue",
    priority: "medium",
    createdAt: "2024-06-19T14:15:00Z",
    updatedAt: "2024-06-19T14:15:00Z",
  },
  {
    id: "3",
    projectId: "2",
    title: "Environmental Permits Approved",
    content: "All environmental compliance permits have been approved by DENR. Project can now proceed to the next phase of construction.",
    author: "Maria Santos",
    type: "milestone",
    priority: "high",
    createdAt: "2024-06-18T09:00:00Z",
    updatedAt: "2024-06-18T09:00:00Z",
  },
];

export const mockSafetyIncidents: SafetyIncident[] = [
  {
    id: "1",
    projectId: "1",
    incidentDate: "2024-06-15",
    description: "Minor cut on hand while handling steel reinforcement",
    severity: "minor",
    location: "Building A - 5th Floor",
    involvedPersonnel: ["Worker-001: Pedro Sanchez"],
    rootCauseAnalysis: "Inadequate personal protective equipment usage",
    preventiveActions: "Mandatory glove inspection and replacement program implemented",
    isoStandards: ["ISO 45001:2018"],
    status: "resolved",
    createdAt: "2024-06-15T11:30:00Z",
    updatedAt: "2024-06-16T08:00:00Z",
  },
];

export const mockWorkerCertifications: WorkerCertification[] = [
  {
    id: "1",
    workerId: "W001",
    workerName: "Pedro Sanchez",
    certificationType: "Heavy Equipment Operator",
    certificationNumber: "HEO-2024-001",
    issuingAuthority: "TESDA",
    issueDate: "2024-01-15",
    expiryDate: "2026-01-15",
    status: "active",
    isoCompliance: ["ISO 45001:2018"],
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
];

export const mockSafetyTrainingRecords: SafetyTrainingRecord[] = [
  {
    id: "1",
    workerId: "W001",
    workerName: "Pedro Sanchez",
    trainingType: "Fall Protection Training",
    trainingDate: "2024-06-01",
    trainer: "Safety Instructor Lopez",
    duration: 8,
    completionStatus: "completed",
    certificationEarned: "Fall Protection Certificate",
    nextTrainingDue: "2025-06-01",
    isoStandards: ["ISO 45001:2018"],
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
];

export const mockResources: Resource[] = [
  {
    id: "1",
    name: "Caterpillar 320D Excavator",
    type: "equipment",
    description: "Heavy-duty excavator for foundation work",
    status: "in-use",
    location: "Metro Manila Residential Complex - Site A",
    projectId: "1",
    acquisitionDate: "2023-12-01",
    cost: 3500000,
    repairHistory: [
      {
        id: "1",
        date: "2024-05-15",
        description: "Hydraulic pump replacement",
        partsReplaced: ["Hydraulic pump", "Oil filter"],
        cost: 85000,
        technician: "Technician Garcia",
        nextMaintenanceDate: "2024-08-15",
      },
    ],
    createdAt: "2023-12-01T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "2",
    name: "Steel Reinforcement Bars",
    type: "material",
    description: "Grade 60 rebar for structural concrete",
    status: "available",
    location: "Warehouse B",
    acquisitionDate: "2024-06-10",
    cost: 150000,
    createdAt: "2024-06-10T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
];

export const mockComplianceItems: ComplianceItem[] = [
  {
    id: "1",
    projectId: "1",
    documentType: "Building Permit",
    description: "Municipal building permit for residential complex",
    requiredBy: "Makati City Hall",
    dueDate: "2024-07-01",
    status: "approved",
    assignee: "Juan dela Cruz",
    notes: "Permit approved with standard conditions",
    submissionDate: "2024-06-01",
    approvalDate: "2024-06-15",
    createdAt: "2024-05-15T00:00:00Z",
    updatedAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "2",
    projectId: "1",
    documentType: "Environmental Compliance Certificate",
    description: "ECC for construction activities",
    requiredBy: "DENR",
    dueDate: "2024-08-01",
    status: "in-progress",
    assignee: "Environmental Officer Cruz",
    notes: "Awaiting final review from DENR regional office",
    submissionDate: "2024-06-10",
    createdAt: "2024-05-20T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
];

export const mockCCTVCameras: CCTVCamera[] = [
  {
    id: "1",
    name: "Main Gate Camera",
    location: "Main Entrance",
    ipAddress: "192.168.1.101",
    status: "online",
    type: "fixed",
    resolution: "1080p",
    installDate: "2024-01-15",
    lastMaintenance: "2024-06-01",
    nextMaintenance: "2024-09-01",
    projectId: "1",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Construction Site Overview",
    location: "Site Center",
    ipAddress: "192.168.1.102",
    status: "online",
    type: "ptz",
    resolution: "4K",
    installDate: "2024-02-01",
    lastMaintenance: "2024-06-01",
    nextMaintenance: "2024-09-01",
    projectId: "1",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  totalProjects: 15,
  activeProjects: 8,
  completedProjects: 5,
  totalBudget: 850000000,
  spentBudget: 425000000,
  safetyIncidents: 3,
  tasksCompleted: 1247,
  resourceUtilization: 78,
};
