// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aooppgijnjxbsylvwukx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvb3BwZ2lqbmp4YnN5bHZ3dWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDQ0MDIsImV4cCI6MjA2NzA4MDQwMn0.2vEloPd7dETWTz7GwWMBSexXh70HQPm4RNP2BewozjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});